name: Compile Examples

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      UNIVERSAL_LIBRARIES: |
        - source-path: ./

      SKETCHES_REPORTS_PATH: sketches-reports

    strategy:
      fail-fast: false
      matrix:
        board:
          # - fqbn: esp8266:esp8266:generic
          #   platforms: |
          #     - name: esp8266:esp8266
          #       source-url: http://arduino.esp8266.com/stable/package_esp8266com_index.json
          - fqbn: esp32:esp32:esp32
            platforms: |
              - name: esp32:esp32
                source-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          # - fqbn: rp2040:rp2040:rpipico
          #   platforms: |
          #     - name: rp2040:rp2040
          #       source-url: https://github.com/earlephilhower/arduino-pico/releases/download/global/package_rp2040_index.json

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Install ESP32 platform dependencies
      #   if: startsWith(matrix.board.fqbn, 'esp32:esp32')
      #   run: pip3 install pyserial

      - name: Compile examples
        uses: arduino/compile-sketches@v1
        with:
          cli-compile-flags: |
            - --warnings="none"
          fqbn: ${{ matrix.board.fqbn }}
          platforms: ${{ matrix.board.platforms }}
          enable-deltas-report: true
          sketches-report-path: ${{ env.SKETCHES_REPORTS_PATH }}
          libraries: |
            - source-path: ./
            - name: LinkedList


      - name: Save memory usage change report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.SKETCHES_REPORTS_PATH }}
          path: ${{ env.SKETCHES_REPORTS_PATH }}
